### ISSUE TITLE
Linux slaves disconnect intermittently

### ISSUE THREAD

**Issue by ankitgupta07** [jenkinsci/ssh-slaves-plugin#69]
We are running into a strange issue where the linux slaves would disconnect intermittently (happening at least once a day) with the below error:

```channel stopped
Slave JVM has terminated. Exit code=0
ERROR: [09/11/17 08:00:37] [SSH] Error deleting file.
ha:////4BJzQ5KK22T5KWhPnJrxKFXkoZSAiG2JwcOgVPNHFspbAAAAVx+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P08vOT+vOD8nVc8DzHWtSE4tKMnMz/PLL0mV3NWzufebKBsTA0NFEYMUmgZnCA1SyAABjCCFBQC2xNaiYAAAAA==com.trilead.ssh2.SFTPException: No such file (SSH_FX_NO_SUCH_FILE: A reference was made to a file which does not exist.)
        at com.trilead.ssh2.SFTPv3Client.expectStatusOKMessage(SFTPv3Client.java:555)
        at com.trilead.ssh2.SFTPv3Client.rm(SFTPv3Client.java:973)
        at hudson.plugins.sshslaves.SSHLauncher$3.run(SSHLauncher.java:1255)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[09/11/17 08:00:37] [SSH] Connection closed.
```

Jenkins version = 2.60.3
SSH Slave Plugin = 1.11
JDK = 1.8
Master OS = CentOS 6
Slave OS = CentOS 7

**Comment by oleg-nenashev** [comment]
Could you please raise the issue in Jenkins JIRA?  https://issues.jenkins-ci.org/
I suppose there are already duplicates since it's a Trilead Issue (CC @paladox and @mc1arke)

----
Off-topic: @jglick @olivergondza should we just disable Issues in this repo?

**Comment by olivergondza** [comment]
I agree with Oleg this needs to be filed in JIRA as it is likely unrelated to this plugin. It seems `ssh-slaves` plugin does not expect the `slave.jar` might be gone after the agent was disconnected and fails deleting file that does not exist. Note that this failure effectively obscure *why* did the agent connection got broken on the first place.

**Comment by paladox** [comment]
Hi, looks like your using an older version of this plugin 1.11. 1.21 is available and was updated to support the trilead update. Also please try jenkins 2.73.1.

It looks like he is also using sftp. I’ve only tested with ssh.

**Comment by nfalco79** [comment]
I have the same issue on 3 linux slaves. To fix the problem I move the plugin back to 1.21 and now it's 1 month no more connection lost with slaves.

**Comment by jglick** [comment]
> should we just disable Issues in this repo?

Yes please. @oleg-nenashev I think you have the admin access to do that.

**Comment by oleg-nenashev** [comment]
Moved it to https://issues.jenkins-ci.org/browse/JENKINS-47736
